import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const tracker = fs.readFileSync(path.join(root, "scripts/hooks/tracker.mjs"), "utf8");
const ring = fs.readFileSync(path.join(root, "scripts/apps/action-ring.mjs"), "utf8");
const settings = fs.readFileSync(path.join(root, "scripts/settings.mjs"), "utf8");
const styles = fs.readFileSync(path.join(root, "styles/skjadlborg.css"), "utf8");

assert.doesNotMatch(tracker, /initialize-combat|disable-combat/);
assert.doesNotMatch(tracker, /AOV_SKJADLBORG\.RoundLabel/);
assert.match(tracker, /if \(!AoVAdapter\.enabledSetting\) return;/);
assert.doesNotMatch(tracker, /open-hud|CombatHUD|skj-phasebar-tools/);
assert.match(tracker, /data-tooltip="\$\{safeLabel\}"/);
assert.doesNotMatch(tracker, /title="\$\{safeLabel\}"/);
assert.match(tracker, /aria-current="step"/);
assert.match(tracker, /\[PHASES\.INTENT\]: "fa-comment-dots"/);
assert.match(tracker, /\[PHASES\.BOOKKEEPING\]: "fa-scroll"/);
assert.match(tracker, /findCombatantControlRow/);
assert.match(tracker, /const effects = controls\.querySelector\("\.token-effects"\)/);
assert.match(tracker, /effects\.insertAdjacentHTML\("beforebegin", statusHtml\)/);
assert.match(tracker, /controls\.insertAdjacentHTML\("beforeend", statusHtml\)/);
assert.doesNotMatch(tracker, /state\.phase !== PHASES\.INTENT[\s\S]*?adjustInit/);
assert.doesNotMatch(tracker, /querySelectorAll\(\"\.adjustInit\"\)[\s\S]*?style\.display/);
assert.match(tracker, /className: "reactions"/);
assert.match(tracker, /label: `\$\{localize\("AOV_SKJADLBORG\.Labels\.Reactions"\)\}: \$\{reactionPenalty\}%`/);
assert.match(tracker, /text: `\$\{reactionPenalty\}%`/);
assert.doesNotMatch(tracker, /text: `\$\{localize\("AOV_SKJADLBORG\.Labels\.Reactions"\)/);
assert.doesNotMatch(tracker, /reactionCount \?\? 0\} \(\$\{reactionPenalty\}%\)/);
assert.doesNotMatch(tracker, /className: "dex"/);
assert.doesNotMatch(tracker, /className: "move"/);
assert.match(tracker, /status-action skj-pill skj-combatant-status/);
assert.match(tracker, /const text = status !== INTENT_STATUS\.UNCOMMITTED && categoryLabel[\s\S]*?\? categoryLabel[\s\S]*?: statusLabel;/);
assert.match(tracker, /const label = status !== INTENT_STATUS\.UNCOMMITTED && categoryLabel[\s\S]*?`\$\{statusLabel\}: \$\{categoryLabel\}`/);
assert.match(tracker, /text\n  \}\);/);
assert.match(tracker, /MOVEMENT_PLAN_STATUS\.COMPLETED/);
assert.match(tracker, /MOVEMENT_PLAN_STATUS\.STOPPED/);
assert.doesNotMatch(tracker, /movementStatus !== "none"/);

assert.match(styles, /\.skj-phase-buttons\s*\{[\s\S]*?grid-template-columns:\s*repeat\(4, minmax\(0, 1fr\)\)/);
assert.doesNotMatch(styles, /skj-visually-hidden|skj-phasebar-tools/);
assert.match(styles, /\.skj-actions,[\s\S]*?\.skj-hud-phases\s*\{[\s\S]*?display:\s*flex/);
assert.match(styles, /\.skj-phasebar \.skj-button\s*\{[\s\S]*?min-height:\s*30px/);
assert.doesNotMatch(tracker, /<span>\$\{safeLabel\}<\/span>/);
assert.doesNotMatch(styles, /\.skj-phasebar \.skj-button span/);
assert.match(styles, /\.skj-phasebar \.skj-button i\s*\{[\s\S]*?font-size:\s*15px/);
assert.doesNotMatch(styles, /\.skj-phasebar-main strong/);
assert.doesNotMatch(tracker, /<div class="skj-combatant-row">/);
assert.match(tracker, /renderCombatantStatus\(state\)/);
assert.match(styles, /\.skj-combatant-indicators\s*\{[\s\S]*?overflow:\s*visible/);
assert.match(styles, /\.skj-combatant-indicators\s*\{[^}]*flex-wrap:\s*nowrap;[^}]*overflow:\s*hidden;[^}]*width:\s*100%;/s);
assert.match(styles, /\.skj-tracker-indicator\.readied-weapon\s*\{[^}]*flex:\s*0 1 auto;[^}]*max-width:\s*72px;[^}]*min-width:\s*36px;/s);
assert.match(styles, /\.skj-tracker-indicator\.readied-weapon > span\s*\{[^}]*text-overflow:\s*ellipsis;/s);
assert.match(styles, /\.skj-tracker-indicator\s*\{[\s\S]*?max-width:\s*none/);
assert.match(styles, /\.skj-combatant-status-fallback\s*\{/);
assert.match(styles, /\.skj-combatant-status\s*\{[^}]*flex:\s*0 1 auto;[^}]*max-width:\s*92px;[^}]*min-width:\s*0;[^}]*overflow:\s*hidden;/s);
assert.match(styles, /\.skj-combatant-status > span\s*\{[^}]*text-overflow:\s*ellipsis;/s);
assert.match(styles, /\.combatant-controls > \.skj-combatant-status\s*\{[^}]*margin-inline:\s*3px 2px;/s);
assert.doesNotMatch(styles, /\.skj-combatant-row\s*\{/);

assert.match(ring, /game\.settings\.get\(MODULE_ID, "enableActionRing"\)/);
assert.match(ring, /Hooks\.on\("renderTokenHUD"/);
assert.match(ring, /Hooks\.on\("controlToken"/);
assert.doesNotMatch(ring, /getFlag\(MODULE_ID, "combatState"\)\?\.enabled/);
assert.match(settings, /onChange:\s*\(\) => \{[\s\S]*?ui\.combat\?\.render\?\.\(\)/);

process.stdout.write("tracker layout tests passed\n");
